server.port: 9008
spring:
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: http://localhost:9006/
          predicates:
            - Path=/v1/members/**

        - id: article-service
          uri: http://localhost:9000/
          predicates:
            - Path=/v1/articles/**

        - id: comment-service
          uri: http://localhost:9001/
          predicates:
            - Path=/v1/comments/**

        - id: like-service
          uri: http://localhost:9002/
          predicates:
            - Path=/v1/article-likes/**

        - id: videocall-service
          uri: http://localhost:9021
          predicates:
            - Path=/v1/video-calls/**

        - id: videocall-ws
          uri: ws://localhost:9021
          predicates:
            - Path=/ws/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG