server.port: 9008
spring:
  cloud:
    gateway:
      httpclient:
        websocket:
          enabled: true

      routes:
        - id: livemarket-videocall-ws
          uri: ws://localhost:9021
          predicates:
            - Path=/ws/video-calls/**
          filters:
            - RemoveRequestHeader=Cookie


        - id: livemarket-videocall-sse
          uri: http://localhost:9021
          predicates:
            - Path=/v1/video-call-notify/sse
          filters:
            - RemoveRequestHeader=Cookie


        - id: member-service
          uri: http://localhost:9006/
          predicates:
            - Path=/v1/members/**
        - id: livemarket-article-service
          uri: http://localhost:9000/
          predicates:
            - Path=/v1/articles/**
        - id: livemarket-comment-service
          uri: http://localhost:9001/
          predicates:
            - Path=/v1/comments/**
        - id: livemarket-like-service
          uri: http://localhost:9002/
          predicates:
            - Path=/v1/article-likes/**
        - id: livemarket-videocall-service
          uri: http://localhost:9021
          predicates:
            - Path=/v1/video-calls/**
        - id: article-image-service
          uri: http://localhost:9007
          predicates:
            - Path=/v1/article-images/**
        - id: livemarket-view-service
          uri: http://localhost:9003
          predicates:
            - Path=/v1/article-views/**
        - id: livemarket-hot-article-service
          uri: http://localhost:9004
          predicates:
            - Path=/v1/hot-articles/**
        - id: livemarket-chat-service
          uri: http://localhost:9020
          predicates:
            - Path=/v1/chat/**
        - id: livemarket-notify-ws
          uri: ws://localhost:9020
          predicates:
            - Path=/notify/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: livemarket-chat-ws
          uri: ws://localhost:9020
          predicates:
            - Path=/ws/chat/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: livemarket-video-stomp
          uri: ws://localhost:9020
          predicates:
            - Path=/ws/video-calls/**
          filters:
            - RemoveRequestHeader=Cookie

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
